Export CCustomOutfit class into lua
OpenXRay/xray-16 pull request #1003
Opened 2022-04-11 20:22 UTC by ChugunovRoman

2022-04-25 20:29 UTC, Xottab-DUTY requested changes

2022-04-25 20:29 UTC, Xottab-DUTY commented on src/xrGame/CMakeLists.txt
> +        -g0
Formatting

2022-04-26 06:12 UTC, ChugunovRoman commented on src/xrGame/CMakeLists.txt
> +        -g0
@Xottab-DUTY fixed

2022-12-02 22:40 UTC, Xottab-DUTY approved these changes

2022-12-02 22:40 UTC, merged