Removed inappropriate effects for EFX on default sounds.
OpenXRay/xray-16 pull request #1297
Opened 2023-04-15 23:50 UTC by johncurley

This is a temporary patch that lowers the default gain for EFX in line with EAX and also reverts AL_EFFECTSLOT_AUXILIARY_SEND_AUTO to false so it does not play on sound channels that it is not triggered for. This is a temporary patch until an actual working 3D sound implementation can be engineered as the original games did not have zone files and therefore no real way to zone audio effects.

2023-04-16 00:15 UTC, johncurley commented
This patch should close #1278 until further improvements can be designed and implemented. For now it will cancel the reverb but it is not a true 3D sound environment due to the inability to trigger effects in the environment maps.

2023-04-17 11:09 UTC, Xottab-DUTY commented on src/xrSound/SoundRender_Environment.cpp
> +        RoomLF = fs->r_float();
This is binary file loading, it should not change!

2023-04-17 11:10 UTC, Xottab-DUTY commented on src/xrSound/SoundRender_Environment.cpp
> +        RoomLF = fs->r_float();
File is versioned, so order of loading values should not change.

2023-04-17 11:11 UTC, Xottab-DUTY requested changes
Please, revert changes to `CSoundRender_Environment::load`.

2023-04-18 00:04 UTC, Xottab-DUTY approved these changes

2023-04-18 00:04 UTC, merged