[ClearSky Bugfix]: Fix crash while starting a new game
OpenXRay/xray-16 pull request #1420
Opened 2023-08-16 23:35 UTC by sobkas

Added NULL-checks, skipping not working subitems, increased verbosity of messages
Starting New Game Clear Sky with this change works
Need to also test COP

2023-08-17 09:42 UTC, Xottab-DUTY requested changes

2023-08-17 09:42 UTC, Xottab-DUTY commented on src/xrGame/ui/UIGameTutorial.cpp
Changes to this file totally not needed.
If there's no `game_tutorials.xml`, an assert will be triggered in `CUIXml::Load`. Other changes that add additional logging actually pollute the log.

2023-08-17 09:42 UTC, Xottab-DUTY commented on src/xrGame/ui/UIGameTutorialSimpleItem.cpp
> +    }
This is not needed too

2023-08-17 11:37 UTC, sobkas commented on src/xrGame/ui/UIGameTutorialSimpleItem.cpp
> +    }
Fixed

2023-08-27 20:35 UTC, sobkas commented
Fixed coding style problems

2023-08-28 11:14 UTC, Xottab-DUTY commented on src/xrGame/ui/UIGameTutorial.cpp
> +    }
This is not needed too.
```suggestion
```

2023-08-28 14:46 UTC, sobkas commented on src/xrGame/ui/UIGameTutorial.cpp
> +    }
Fixed

2023-08-28 14:47 UTC, Xottab-DUTY commented
So, I've found the real culprit of this crash. But we still need some changes to `CUISequenceSimpleItem` to make it more robust!
Let me do them in this PR 🙂

2023-08-28 15:11 UTC, merged

2023-08-28 15:11 UTC, Xottab-DUTY commented
Thank you!