Fix several cases of uninitialized values that were used and caused undefined behavior
OpenXRay/xray-16 pull request #1484
Opened 2023-10-27 13:41 UTC by AMS21

2023-10-27 18:00 UTC, Xottab-DUTY requested changes
Some minor codestyle changes needed.

2023-10-27 18:00 UTC, Xottab-DUTY commented on src/xrServerEntities/xrServer_Objects_ALife.cpp
> +    : CSE_ALifeDynamicObjectVisual(caSection), CSE_PHSkeleton(caSection), freezed{false}
Entire codebase uses parentheses in the initializer list, so using braces would look like an alien :)
```suggestion
    : CSE_ALifeDynamicObjectVisual(caSection), CSE_PHSkeleton(caSection), freezed(false)
```

2023-10-27 18:00 UTC, Xottab-DUTY commented on src/xrGame/stalker_animation_manager.h
> +    bool m_call_global_callback{false};
For braces, we always insert spaces inside them.
```suggestion
    bool m_call_script_callback{ false };
    bool m_call_global_callback{ false };
```

2023-10-28 08:57 UTC, AMS21 commented
There should no more aliens be around :)

2023-10-28 11:15 UTC, Xottab-DUTY approved these changes

2023-10-28 11:15 UTC, merged

2023-10-28 11:18 UTC, Xottab-DUTY commented on src/xrGame/obstacles_query_inline.h
> +    m_actual = true;
Comment for future, if someone would investigate something:
`m_actual` wasn't set to any value and setting it to `true` here is correct – `m_obstacles` at empty at this point, so there's no point to call `compute_area()` function which `m_actual` is only used for.