Improve build system
OpenXRay/xray-16 pull request #160
Opened 2017-01-27 21:49 UTC by Armada651

This is a work-in-progress to improve the build process:

- [x] Automatically build luajit
- [x] Don't build the unmaintained editor projects
- [] Add every external project as a submodule

The goal is to be able to do a simple `git clone --recursive` to pull in all dependencies and allow the developer to simply hit Build Solution without errors.

2017-02-06 22:07 UTC, jakebriggs commented
I still had to compile luajit from the command line before everything compiled - but once I did that, it compiled fine.

2017-03-10 15:20 UTC, andrew-boyarshin commented
@Armada651 why have you decided to switch to static build of Crypto++? FIPS conformance is not required by OpenXRay engine (we do not handle money or sensitive user data), plus both before and after this commit we cannot claim to be FIPS conformant.

2017-03-10 15:23 UTC, Armada651 commented
@andrew-boyarshin That's exactly the reason why I switched to a static build. Crypto++ automatically does some FIPS validation tests if it's a DLL build, most notably it checks the hash of the DLL which fails because I didn't include the hash in the output DLL.

Also it is only used in a very small part of the engine, namely checking if certain resource files are "pure" during online gameplay.

2017-03-10 15:26 UTC, andrew-boyarshin commented
@Armada651 oh, I see. I was not aware of runtime validation tests, and their website was not informative enough to tell me that fact.

2017-03-12 11:48 UTC, andrew-boyarshin commented
Tried out and confirmed to be working. Looks Good To Me.

2017-03-18 13:46 UTC, andrew-boyarshin commented
What has changed so that you've force-pushed?

2017-03-18 14:12 UTC, Xottab-DUTY commented
@andrew-boyarshin he just rebased his branch to the latest commits after merging my PRs. 
P.S. So, the branch isn't updated to the latest merged precompiled shaders PR.

2017-03-19 11:16 UTC, Armada651 commented
That doesn't matter as long as there are no merge conflicts.

2017-03-26 16:35 UTC, andrew-boyarshin requested changes
Debug:
Works fine, no flaws, although I also had to apply xrSound CDB library linking fix from another PR for Debug code to compile.

Release:
I had some troubles. zlib in Release mode requires contrib asm linked in. After building these asm files (manually, does not quite match the task of the PR) and successfully linking it with the rest of the zlib I've encountered issue with BugTrap not being able to link to it due to SAFESEH enabled ("no pure asm" requirement).
This should be resolved in order to be able to merge it. Of course removing ASMV and ASMINF preprocessor flags helped to resolve the issue. And taking into consideration asm code is considered experimental in zlib - I think that's the way to go.

2017-03-30 19:48 UTC, Armada651 commented
@andrew-boyarshin Issues are fixed, I opted to disable the assembler code, because it doesn't seem like it wasn't used before either.

2017-03-31 03:05 UTC, andrew-boyarshin commented
@Armada651 will check this out and update my review.

2017-04-10 00:29 UTC, Armada651 commented
Since no one seems to disagree with these changes following the review I'm going to merge them tomorrow. Let me know if anyone has time to do a full review.

2017-04-10 00:48 UTC, andrew-boyarshin commented
In fact, I've reviewed your modifications and they look good to me. I just had little time to do the thorough testing in the game.

2017-04-10 00:50 UTC, andrew-boyarshin approved these changes

2017-04-10 00:51 UTC, Armada651 commented
The only real risk is to this PR is that fact that the change to Crypto++ is mostly untested (only some sanity tests were done). The only consequence of that would be that it would break "pure" multiplayer. I don't think multiplayer is a priority anyway, so if it turns out we broke that we can fix it later.

2017-04-10 10:43 UTC, merged