Glew to epoxy
OpenXRay/xray-16 pull request #1681
Opened 2024-05-25 20:17 UTC by sobkas

Switch from ancient GLEW to libepoxy

2024-05-26 12:27 UTC, AMS21 commented
libepoxys last release is 2 years old so why not use the still actively developed [glad](https://github.com/Dav1dde/glad) library, which also supports Vulkan out of the box?

2024-05-26 16:50 UTC, sobkas commented
> libepoxys last release is 2 years old so why not use the still actively developed [glad](https://github.com/Dav1dde/glad) library, which also supports Vulkan out of the box?

GLAD2 depends on generated code and this code is separated for each API.
So for each API  there are files(*.c and *.h) that would be included into OpenXRay.
Epoxy needs only #include to be added.

2024-05-26 17:44 UTC, Xottab-DUTY commented
> libepoxys last release is 2 years old so why not use the still actively developed [glad](https://github.com/Dav1dde/glad) library, which also supports Vulkan out of the box?

GLEW's last release is 3 years old :)

Though, there's a bad sign there: libepoxy doesn't have any fresh commits since the last release, while glew has.

2024-05-26 18:17 UTC, sobkas commented
> > libepoxys last release is 2 years old so why not use the still actively developed [glad](https://github.com/Dav1dde/glad) library, which also supports Vulkan out of the box?
> 
> GLEW's last release is 3 years old :)
> 
> Though, there's a bad sign there: libepoxy doesn't have any fresh commits since the last release, while glew has.

libepoxy is used by much more recent software, while glew usage is ancient.

2024-05-26 19:05 UTC, Xottab-DUTY requested changes
Thanks!
I've left mostly code style and some other small improvement request!

2024-05-26 19:05 UTC, Xottab-DUTY commented on src/Layers/xrRenderGL/glHW.cpp
```suggestion
#include "xrEngine/XR_IOConsole.h"

#include <epoxy/gl.h>

```

2024-05-26 19:05 UTC, Xottab-DUTY commented on src/Layers/xrRenderGL/glHW.cpp
> +        // Apply the pixel format to the device context
```suggestion
    mode.format = SDL_PIXELFORMAT_RGBA8888;
    // Apply the pixel format to the device context
```

2024-05-26 19:05 UTC, Xottab-DUTY commented on src/Layers/xrRenderGL/glHW.cpp
> +
```suggestion
```

2024-05-26 19:05 UTC, Xottab-DUTY commented on src/Layers/xrRenderGL/glHW.h
> +    bool GLARBvertexattribbindingSupported;
```suggestion
    bool DebugSupported;
    bool TextureFloatSuppoted;
    bool VertexAttribBindingSupported;
```

2024-05-26 19:05 UTC, Xottab-DUTY commented on src/Layers/xrRenderGL/glState.h
> +    bool GLEXTtexturefilteranisotropicSupported;
Let's move it to `HW` with `TextureFilterAnisotropicSupported` name.
It's generally better to keep such stuff in one place, and also `glState` can be created on-demand during the game run – that means it would always call `epoxy_has_gl_extension` for each glState instance (there can be many of them) which is suboptimal.

2024-05-26 19:05 UTC, Xottab-DUTY commented on src/Layers/xrRenderGL/glBufferUtils.cpp
> +void ConvertVertexDeclaration(const VertexElement* dxdecl, SDeclaration* decl, bool GLARBvertexattribbindingSupported)
This looks less good.
It's better to just use `HW.GLARBvertexattribbindingSupported` (after renaming it should be `HW.VertexAttribBindingSupported`) directly.

2024-05-26 19:05 UTC, Xottab-DUTY commented on src/Layers/xrRender/ShaderResourceTraits.h
> +    if (epoxy_gl_version() >= 43)
Let's check for `HW.OpenGLVersion` instead of calling external function.

2024-05-26 19:05 UTC, Xottab-DUTY commented on cmake/Findepoxy.cmake
Please, try to use this find module: https://github.com/WebKit/WebKit/blob/main/Source/cmake/FindEpoxy.cmake
It provides `Epoxy::Epoxy` CMake target which can be used.

2024-05-26 19:05 UTC, Xottab-DUTY commented on src/Layers/xrRenderPC_GL/CMakeLists.txt
> +    "${epoxy_INCLUDE_DIR}"
Can be removed after switching to `Epoxy::Epoxy`.

2024-05-26 19:05 UTC, Xottab-DUTY commented on src/Layers/xrRenderPC_GL/CMakeLists.txt
> +    "${epoxy_LIBRARY}"
Switch to `Epoxy::Epoxy`.

2024-05-27 09:12 UTC, AMS21 commented
> > libepoxys last release is 2 years old so why not use the still actively developed [glad](https://github.com/Dav1dde/glad) library, which also supports Vulkan out of the box?
> 
> GLEW's last release is 3 years old :)
> 
> Though, there's a bad sign there: libepoxy doesn't have any fresh commits since the last release, while glew has.



> > libepoxys last release is 2 years old so why not use the still actively developed [glad](https://github.com/Dav1dde/glad) library, which also supports Vulkan out of the box?
> 
> GLEW's last release is 3 years old :)
> 
> Though, there's a bad sign there: libepoxy doesn't have any fresh commits since the last release, while glew has.

Maybe I'm being missunderstood here I'm all for replacing the ancient GLEW library. My point was rather to maybe consider using the glad library I linked which latest release is about 1 Month old and still actively developed while also supporting all OpenGL extensions as well as Vulkan (which we might want to use in the future). Also glad directly parses the official OpenGL and Vulkan spec to generate it's glue code so even if the library is ever abandoned the parser should still be able to generate bindings for never versions of OpenGL and Vulkan (at least untill they make fundamental changes to the spec).

2024-05-28 17:02 UTC, Xottab-DUTY commented
@AMS21 the concern that @sobkas and I had was this:
> GLAD2 depends on generated code and this code is separated for each API.
So for each API there are files(*.c and *.h) that would be included into OpenXRay.
Epoxy needs only #include to be added.

But I just checked the generated files and found that we were wrong.

GLAD2 supports working with multiple APIs simultaneously. On it's website you just need to select maximal OpenGL version and any lower version would be included.
It also support header-only option.

2024-05-29 17:07 UTC, Xottab-DUTY commented
So main concern with libepoxy is that it's author hadn't been active for two years. No commits, not PR merges, etc.
It also doesn't have simple global variables indicating if an extension is available. Honestly, they are pretty handy to use.

2024-06-01 15:14 UTC, Xottab-DUTY commented
Superseded with #1684.

2024-06-01 15:14 UTC, closed without merging