Fix xrSound wont compile on Debug configuration
OpenXRay/xray-16 pull request #180
Opened 2017-03-25 11:42 UTC by Xottab-DUTY

Unexpected one! Sorry for this.
+ Small include path fixes

2017-03-25 13:06 UTC, CrossVR requested changes

2017-03-25 13:06 UTC, Armada651 commented on src/xrSound/stdafx.cpp
> +#pragma comment(lib, "xrCDB.lib") // Xottab_DUTY: For some reason it wont compile without it.
Why would you put this back into the pre-compiled header when in the last PR you moved library inputs to the project files?

2017-03-25 14:38 UTC, Xottab-DUTY commented on src/xrSound/stdafx.cpp
> +#pragma comment(lib, "xrCDB.lib") // Xottab_DUTY: For some reason it wont compile without it.
Without direct point to xrCDB.lib xrSound wont compile. I can put this in project file, but I think we should investigate in future into this (Why in debug just only project reference wont work, just like in release). So, it's a reminder in the future.

2017-03-30 15:24 UTC, CrossVR requested changes

2017-03-30 15:24 UTC, Armada651 commented on src/xrSound/stdafx.cpp
> +#pragma comment(lib, "xrCDB.lib") // Xottab_DUTY: For some reason it wont compile without it.
I don't agree with that reasoning, pulling in extra library inputs for the linker is not a problem at all. You don't even need to limit it to the Debug configuration. Only objects from the library that are actually used will be linked to.

Please move this to the project file, then we can merge this PR.

2017-03-30 15:56 UTC, CrossVR approved these changes

2017-03-30 15:57 UTC, merged