Make tbb memory allocator optional
OpenXRay/xray-16 pull request #305
Opened 2018-12-26 19:58 UTC by culhatsker

`tbb allocator` causes errors on Linux systems with opensource GPU drivers.
Made it optional for Windows and turned off by default on Linux.

2018-12-26 20:17 UTC, eagleivg requested changes

2018-12-26 20:17 UTC, eagleivg commented on src/xrCore/xrMemory.cpp
> +    // scalable_allocation_command(TBBMALLOC_CLEAN_ALL_BUFFERS, nullptr);
Ну спрячь уж тогда под USE_TBB_ALLOCATOR, зачем комментировать-то?

2018-12-26 20:17 UTC, eagleivg commented on src/xrCore/xrMemory.h
> +        return xr_internal_malloc(size);
в оригинале тут не прочто size, а size + reserved, иначе у тебя начнутся переполнения буфера.

2018-12-26 20:17 UTC, eagleivg commented on src/xrCore/xrMemory.h
> +        return xr_internal_realloc(ptr, new_size);
И здесь тоже + reserved

2018-12-26 20:19 UTC, eagleivg commented on src/xrCore/xrMemory.cpp
> +    // scalable_allocation_command(TBBMALLOC_CLEAN_ALL_BUFFERS, nullptr);
И не забудь, это должно ещё под виндой собираться, там USE_TBB_ALLOCATOR не определен (кстати говоря, под виндой движок вообще не работает со стандартным аллокатором)

2018-12-26 20:19 UTC, culhatsker commented on src/xrCore/xrMemory.h
> +        return xr_internal_malloc(size);
упс, и правда, помнится такое, поправим

2018-12-27 09:45 UTC, eagleivg commented on src/xrCore/xrMemory.h
> +#include <tbb/scalable_allocator.h>
Забыл #include <tbb/tbb_allocator.h>, см. тревис и аппвейор

2018-12-27 19:17 UTC, andrew-mcmahon commented
These changes have gotten the game working on my R9 285 as you can [see here](https://imgur.com/a/ZqKzDf8)  
  
**git clone https://github.com/culhatsker/xray-16.git --branch optional_allocation --single-branch --recurse-submodules**

Prone to crashing (hitting ESC) and performance isn't great yet but that's to be expected at this point.
[openxray_mwnn.log](https://github.com/OpenXRay/xray-16/files/2713136/openxray_mwnn.log)  
  
Brilliant work! Thanks to everyone.

2018-12-27 20:19 UTC, merged