Unload all ammo
OpenXRay/xray-16 pull request #459
Opened 2019-09-04 20:50 UTC by Dx74rghs

Functionality to unload all ammo from available weapons in the backpack.

2019-09-04 21:01 UTC, Xottab-DUTY requested changes
I can't accept this PR as is. This introduces gamedata changes, which we try to keep close to vanilla as possible.

You can do it another way: try to add a context menu entry with string "Unload all". Yes, it's not a hotkey, but this is a good compromise between introducing new features and being close to vanilla as possible.

Also, do not put the translations into original `ui_st_keybinding.xml`, instead use `openxray.xml`.

2019-09-05 10:35 UTC, Dx74rghs commented
added as context menu item

2019-09-05 12:10 UTC, Xottab-DUTY approved these changes

2019-09-05 12:45 UTC, Xottab-DUTY commented
Thank you!

2019-09-05 12:47 UTC, merged