CHW: WSI surface parameters encapsulated
OpenXRay/xray-16 pull request #465
Opened 2019-09-08 20:59 UTC by vTurbine

This removes implementation specific access to rendering surface dimensions.

2019-09-08 21:07 UTC, Xottab-DUTY requested changes
I'm not sure, that `SIZE` is Linux compatible. But even if it is, consider to use std::pair and C++17 syntax:
```cpp
class HW
{
	...
	std::pair<u32, u32> GetSurfaceSize() const;
	...
};
...

auto [width, height] = HW.GetSurfaceSize();
```

2019-09-08 21:10 UTC, Xottab-DUTY commented
Yes, according to Travis CI, type `SIZE` is Windows-only, which is not suitable for us.

2019-09-09 05:14 UTC, vTurbine commented
Expected smth like this. But saw GL renderer using ‘HDC’

2019-09-09 08:05 UTC, vTurbine commented
The master is broken

2019-09-11 16:45 UTC, Xottab-DUTY commented on src/Layers/xrRenderDX10/dx10HW.cpp
> +    return {
`{` should be on the next line.

2019-09-11 16:45 UTC, Xottab-DUTY commented on src/Layers/xrRenderGL/glHW.cpp
> +    return {
`{` should be on the next line.

2019-09-11 16:45 UTC, Xottab-DUTY commented on src/Layers/xrRenderDX9/dx9HW.cpp
> +    return {
`{` should be on the next line.

2019-09-15 13:44 UTC, Xottab-DUTY approved these changes

2019-09-23 19:37 UTC, merged