Porting engine to ARM64 architecture
OpenXRay/xray-16 pull request #532
Opened 2019-12-23 09:14 UTC by Zigatun

2019-12-24 08:23 UTC, Xottab-DUTY commented on src/xrCore/Math/MathUtil.cpp
> +
Please, remove that empty added space.

2019-12-24 08:42 UTC, Zigatun commented on src/xrCore/Math/MathUtil.cpp
> +
I fixed this.

2020-03-13 12:42 UTC, q4a requested changes
Please, fix few spaces.

2020-03-13 12:42 UTC, q4a commented on src/xrCore/Math/MathUtil.cpp
> +	PLCCalc = PLCCalc_CPP;
Replace tabs with 4 space, please. And in else section.
```suggestion
    PLCCalc = PLCCalc_CPP;

2020-03-13 12:42 UTC, q4a commented on src/xrCommon/inlining_macros.h
> +#define DEBUG_BREAK __builtin_trap()
Nice change, thanks!

2020-03-13 12:42 UTC, q4a commented on Externals/sse2neon/sse2neon.h
> +#ifndef SSE2NEON_H
Did you take it from https://github.com/DLTcollab/sse2neon ?

2020-03-13 12:42 UTC, q4a commented on src/xrCore/Math/MathUtil.cpp
> +	PLCCalc = PLCCalc_SSE;
```suggestion
    PLCCalc = PLCCalc_SSE;

2020-03-13 12:42 UTC, q4a commented on src/xrCore/_math.cpp
> +  return virtual_timer_value;
Use 4 space, please.
```suggestion
    int64_t virtual_timer_value;
    asm volatile("mrs %0, cntvct_el0" : "=r"(virtual_timer_value));
    return virtual_timer_value;

2020-03-13 16:50 UTC, merged