xrRender: added stream buffers abstraction
OpenXRay/xray-16 pull request #573
Opened 2020-04-07 08:28 UTC by vTurbine

Just for build check.
NOT TESTED

2020-04-07 10:08 UTC, vTurbine commented
Todo (not in this pr)
- base class for staging/stream buffers;
- stream buffer in dx10ConstantBuffer

2020-04-07 12:12 UTC, Xottab-DUTY requested changes

2020-04-07 12:12 UTC, Xottab-DUTY commented on src/Layers/xrRender/BufferUtils.h
> + * The are two modes of mapping available:
```suggestion
 * There are two modes of mapping available:
```

2020-04-07 12:12 UTC, Xottab-DUTY commented on src/Layers/xrRenderDX10/dx10BufferUtils.cpp
> +
```suggestion
```

2020-04-07 12:12 UTC, Xottab-DUTY commented on src/Layers/xrRenderDX10/dx10BufferUtils.cpp
> +    bool bImmutable, D3D_BIND_FLAG BufferType)
```suggestion
    bool bImmutable, D3D_BIND_FLAG bufferType)
```

2020-04-07 12:12 UTC, Xottab-DUTY commented on src/Layers/xrRenderDX10/dx10BufferUtils.cpp
> +    desc.BindFlags = BufferType;
```suggestion
    desc.BindFlags = bufferType;
```

2020-04-07 12:12 UTC, Xottab-DUTY commented on src/Layers/xrRenderDX10/dx10BufferUtils.cpp
> +    desc.Usage = bImmutable ? D3D_USAGE_DEFAULT : D3D_USAGE_DYNAMIC;
Variable changes meaning. Let's don't do such things.

2020-04-07 12:35 UTC, vTurbine commented on src/Layers/xrRenderDX10/dx10BufferUtils.cpp
> +    bool bImmutable, D3D_BIND_FLAG BufferType)
So why still `DataSize` then?

2020-04-07 12:36 UTC, Xottab-DUTY commented on src/Layers/xrRenderDX10/dx10BufferUtils.cpp
> +    bool bImmutable, D3D_BIND_FLAG BufferType)
We can rename it too then =)

2020-04-08 20:14 UTC, Xottab-DUTY commented on src/Layers/xrRender/BufferUtils.h
> +    u32 m_RefCounter{ 0 };
```suggestion
    u32 m_RefCounter{};
```

2020-04-08 20:14 UTC, Xottab-DUTY commented on src/Layers/xrRender/BufferUtils.h
> +    u32 m_RefCounter{ 0 };
```suggestion
    u32 m_RefCounter{};
```

2020-04-08 20:14 UTC, Xottab-DUTY commented on src/Layers/xrRenderDX10/dx10BufferUtils.cpp
> +    desc.Usage          = bDynamic ? D3D_USAGE_DYNAMIC : D3D_USAGE_DEFAULT;
I just realized that we can pass `D3D_USAGE` as an function argument, as we did it for `D3D_BIND_FLAG`.

2020-04-08 20:36 UTC, Xottab-DUTY commented on src/Layers/xrRenderDX10/dx10BufferUtils.cpp
> +    void *pData = nullptr;
```suggestion
    void* pData = nullptr;
```

2020-04-08 20:36 UTC, Xottab-DUTY commented on src/Layers/xrRenderDX10/dx10BufferUtils.cpp
> +void* VertexStreamBuffer::Map(size_t offset, size_t size, bool flush /*= false*/)
```suggestion
void* VertexStreamBuffer::Map(size_t offset, size_t /*size/*, bool flush /*= false*/)
```

2020-04-08 20:39 UTC, Xottab-DUTY commented on src/Layers/xrRender/BufferUtils.h
> +
```suggestion
```

2020-04-08 20:39 UTC, Xottab-DUTY commented on src/Layers/xrRender/BufferUtils.h
> +
```suggestion
```

2020-04-08 20:40 UTC, vTurbine commented on src/Layers/xrRender/BufferUtils.h
> +    u32 m_RefCounter{ 0 };
See the same var in the class above

2020-04-08 20:40 UTC, vTurbine commented on src/Layers/xrRenderDX10/dx10BufferUtils.cpp
> +    desc.Usage          = bDynamic ? D3D_USAGE_DYNAMIC : D3D_USAGE_DEFAULT;
Good~

2020-04-08 20:41 UTC, Xottab-DUTY commented on src/Layers/xrRenderDX10/dx10BufferUtils.cpp
> +void* IndexStreamBuffer::Map(size_t offset, size_t size, bool flush /*= false*/)
```suggestion
void* IndexStreamBuffer::Map(size_t offset, size_t /*size*/, bool flush /*= false*/)
```

2020-04-08 20:41 UTC, Xottab-DUTY commented on src/Layers/xrRenderDX10/dx10BufferUtils.cpp
> +    void *pData = nullptr;
```suggestion
    void* pData = nullptr;
```

2020-04-08 20:42 UTC, Xottab-DUTY commented on src/Layers/xrRender/BufferUtils.h
> +    u32 m_RefCounter{ 0 };
Should be removed too, but not in this PR =)

2020-04-09 11:07 UTC, merged