Getting rid of BYTE type
OpenXRay/xray-16 pull request #669
Opened 2020-10-01 09:56 UTC by Plotja

#23

2020-10-01 14:00 UTC, nitrocaster commented
Please, use `git commit --amend` and `git push --force` to avoid creating all these 'fix' commits. Forced pushes are OK when you're committing to your own temporary branch.

2020-10-01 14:16 UTC, Plotja commented
> Please, use `git commit --amend` and `git push --force` to avoid creating all these 'fix' commits. Forced pushes are OK when you're committing to your own temporary branch.

You are right. I fixed this.

2020-10-01 14:29 UTC, LVutner commented
Soo, what's the problem with BYTE? There's any point in replacing it?

2020-10-01 14:36 UTC, oldSerpskiStalker commented
If a BYTE is assigned there, why do you change it? Then - oops have us crashes(((
The same goes for the IC if it has a define assigned to it. So don't touch it :ritas:

2020-10-01 15:18 UTC, Plotja commented
> Soo, what's the problem with BYTE? There's any point in replacing it?

Some problems with portability.

2020-10-03 05:55 UTC, Xottab-DUTY requested changes
Please, revert `utils/mp_gpprof_server`.

2020-10-03 08:25 UTC, Xottab-DUTY commented on src/utils/mp_gpprof_server/libraries/gamespy/gt2/gt2action/TGAFile.cpp
> +}
Remove the empty line, please. We don't want to produce the diff for no reason. :)

2020-10-03 08:26 UTC, Xottab-DUTY commented on src/xrGame/RegistryFuncs.cpp
> +    res = RegSetValueEx(hKey, rKeyName, NULL, rKeyType, (u8*)value, KeyValueSize);
Let's use LPBYTE when interacting with WinAPI.

2020-10-03 08:27 UTC, Xottab-DUTY commented on src/xrGameSpy/xrGameSpy.cpp
> +            KeyCDKey, REGISTRY_VALUE_INSTALL_PATCH_ID, NULL, &KeyValueType, (u8*)&KeyValue, &KeyValueSize);
Let's use LPBYTE when interacting with WinAPI.

2020-10-03 08:27 UTC, Xottab-DUTY commented on src/xrGame/RegistryFuncs.cpp
> +    res = RegQueryValueEx(hKey, rKeyName, NULL, &rKeyType, (u8*)rBuf, &KeyValueSize);
Let's use LPBYTE when interacting with WinAPI.

2020-10-03 12:01 UTC, Xottab-DUTY approved these changes

2020-10-03 12:03 UTC, merged