[perf] Minor refactor
OpenXRay/xray-16 pull request #791
Opened 2021-05-08 21:12 UTC by xrombik

2021-05-09 22:22 UTC, Xottab-DUTY requested changes

2021-05-09 22:22 UTC, Xottab-DUTY commented on src/xrCDB/Frustum.cpp
> +    return planes[p_count - 1U].classify(c) <= r;
This actually makes it unsafe, because NODEFAULT won't be triggered.

2021-05-10 06:12 UTC, drug007 commented on src/xrCDB/Frustum.cpp
> +    return planes[p_count - 1U].classify(c) <= r;
Also '0' should be possible value and return `true`

2021-05-10 13:54 UTC, Xottab-DUTY commented on src/xrCDB/Frustum.cpp
> +    return planes[p_count - 1U].classify(c) <= r;
It is still unsafe

2021-05-10 14:56 UTC, drug007 commented on src/xrCDB/Frustum.cpp
> +    return planes[p_count - 1U].classify(c) <= r;
I don't know what `NODEFAULT` is but probably this:
```
if (p_count > 12)
    NODEFAULT;
```

2021-07-10 08:03 UTC, Xottab-DUTY commented on src/xrCDB/Frustum.cpp
> +    return planes[p_count - 1U].classify(c) <= r;
```suggestion
	switch (p_count)
    {
    case 12:
    case 11:
    case 10:
    case 9:
    case 8:
    case 7:
    case 6:
    case 5:
    case 4:
    case 3:
    case 2:
    case 1:
        if (planes[p_count - 1].classify(c) > r)
            return false;
    case 0: break;
    default: NODEFAULT;
    }
    return true;
```

2021-07-10 08:04 UTC, Xottab-DUTY commented on src/xrCDB/Frustum.cpp
> +	switch (p_count)
```suggestion
    switch (p_count)
```

2021-07-10 09:10 UTC, Xottab-DUTY commented on src/xrCDB/Frustum.cpp
> +    return planes[p_count - 1U].classify(c) <= r;
```suggestion
	VERIFY(p_count <= FRUSTUM_MAXPLANES); // '<=' is not a typo, this check is correct
    if (p_count == 0)
        return true;
    return planes[p_count - 1].classify(c) <= r;
```

2021-07-10 09:12 UTC, merged